Out.txt : hello.exe		 #Out.txt is where we save our output to, it depens on hello.exe
	mono hello.exe > Out.txt #run hello.exe, send output to Out.txt

hello.exe : hello.cs		#hello.exe depends on hello.cs
	mcs hello.cs		#compile hello.cs, save bytecode as hello.exe
